/*
21522258 - Nguyen Tran Gia Kiet
21521897 - Thi Thanh Cong
21522684 - Tran Thanh Tin
21522541 - Cao Hoai Sang
*/  


CREATE DATABASE BTL2;
GO
USE BTL2;
GO


CREATE TABLE CUAHANG(
	MACH VARCHAR(5) NOT NULL PRIMARY KEY,
	TENCH VARCHAR(50),
	DIACHI VARCHAR(50),
	PHISHIP MONEY
)

CREATE TABLE KHOANGCACH(
MACH1 VARCHAR(5),
MACH2 VARCHAR(5),
KHCACH INT 
PRIMARY KEY(MACH1,MACH2),
FOREIGN KEY (MACH1) REFERENCES CUAHANG(MACH),
FOREIGN KEY (MACH2) REFERENCES CUAHANG(MACH)
)

CREATE TABLE DIENTHOAI(
	MADT VARCHAR(5) NOT NULL PRIMARY KEY,
	TENDT VARCHAR(50),
	HANGSX VARCHAR(50),
	NAMSX INT,
	MACHLTRU VARCHAR(5),
	GIABAN MONEY,
	SLTON INT,
	FOREIGN KEY (MACHLTRU) REFERENCES CUAHANG(MACH)
)
create table DONHANG(
	MADH VARCHAR(5) NOT NULL PRIMARY KEY,
	TENKH VARCHAR(50),
	NGSINH DATETIME,
	DCSHIP VARCHAR(50),
	MACHBAN VARCHAR(5),
	KCSHIP INT,
	TRIGIADH MONEY,
	FOREIGN KEY (MACHBAN) REFERENCES CUAHANG(MACH)
)

CREATE TABLE CTDH (
	MADH VARCHAR(5) NOT NULL,
	MADT VARCHAR(5) NOT NULL,
	MACHXUAT VARCHAR(5),
	SLMUA INT,
	PRIMARY KEY (MADH, MADT),
	FOREIGN KEY (MADH) REFERENCES DONHANG(MADH),
	FOREIGN KEY (MADT) REFERENCES DIENTHOAI(MADT),	
	FOREIGN KEY (MACHXUAT) REFERENCES CUAHANG(MACH)
)


insert into CUAHANG values ('001','DTA','2/15 q2 hcm', 35000)
insert into CUAHANG values ('002','DTb','2/21 q5 hcm', 35000)
insert into KHOANGCACH values ('001','002', 12)
insert into DIENTHOAI values ('101', 'iphone 5', 'apple', '2005', '001', 5000000, 6)
insert into DIENTHOAI values ('102', 'iphone 7', 'apple', '2007', '002', 7000000, 3)
insert into DONHANG values('201', 'Tran Van A', '06/07/1990', '3/45 thu duc', '001', 20, 5035000)
insert into DONHANG values('202', 'Nguyen Thi A', '06/07/1993', '6/1 q1 hcm', '002', 30, 14035000)
insert into CTDH values('201', '101', '001', 1)
insert into CTDH values('202', '102', '002', 2)


--MAY B
select * from [B216_13].BTL2.dbo.CUAHANG



create procedure ThemCTDH
@MaDH varchar(5),
@MaDT varchar(5),
@SLMua varchar(5)
AS
BEGIN
	DECLARE @MAXUAT varchar(5);
	DECLARE @MACHCAN varchar(5);
	SELECT @MAXUAT = MACHLTRU  FROM DIENTHOAI WHERE @MaDT = MADT;
	if(@MAXUAT is null)
		BEGIN 
			SELECT @MAXUAT = MACHLTRU FROM [B216_13].BTL2.dbo.DIENTHOAI WHERE @MaDT = MADT;
		END
	INSERT INTO CTDH VALUES(@MaDH,@MaDt,@MAXUAT,@SLMua);

END;

create procedure TruSLDT
@MaDH varchar(5),
@MaDT varchar(5),
@SLMua varchar(5)
AS
BEGIN
	DECLARE @MAXUAT varchar(5);
	DECLARE @MACHCAN varchar(5);
	SELECT @MAXUAT = MACHLTRU  FROM DIENTHOAI WHERE @MaDT = MADT;
	if(@MAXUAT is null)
		BEGIN 
			SELECT @MAXUAT = MACHLTRU FROM [B216_13].BTL2.dbo.DIENTHOAI WHERE @MaDT = MADT;
		END
	UPDATE DIENTHOAI SET SLTON = SLTON - @SLMua where @MaDT = MADT AND @MAXUAT=MACHLTRU

END;

EXEC ThemCTDH '202','101',3;
EXEC TruSLDT '202','101',3;



--MAY A
insert into dbo.CUAHANG values ('2123', 'Samsung', 'Bac Lieu', 123123)
select * from [B216_14].BTL2.dbo.CUAHANG;

create proc proc_themCTDH_MAYA
@MADH varchar(5),
@MADT varchar(5),
@SLMUA int
as
begin
	declare @MACNXUAT varchar(5)
	select @MACNXUAT = MACHLTRU from dbo.DIENTHOAI where @MADT = MADT;
	if (@MACNXUAT is null)
	begin
		SELECT @MACNXUAT = MACHLTRU from [B216_14].BTL2.dbo.DIENTHOAI where @MADT = MADT;
	end

	insert into dbo.CTHD values (@MADH, @MADT, @MACNXUAT, @SLMUA);
end;

create proc proc_giamSLDIENTHOAI
@MADH varchar(5),
@MADT varchar(5),
@SLMUA int
as
begin
    declare @SLCU;
	declare @CNBAN;

	select @SLCU = SLTON from dbo.DIENTHOAI where MADT = @MADT;
	select @CNBAN = MACHLTRU from dbo.DIENTHOAI where MADT = @MADT;

	if (@SLCU is null)
	begin
		select @SLCU = SLTON from [B216_14].BLT2.dbo.DIENTHOAI where MADT = @MADT;
	    select @CNBAN = MACHLTRU from [B216_14].BLT2.dbo.DIENTHOAI where MADT = @MADT;

	end
	update dbo.DIENTHOAI set SLTON = @SLCU - @SLMUA where MACHLTRU = @CNBAN and MADT = @MADT;
end;



--TRIGGER

create or alter trigger CapNhapGTDH ON DONHANG
AFTER INSERT AS
BEGIN
	DECLARE @ORDERID VARCHAR(5) 
    DECLARE @PVCDH INT,
    DECLARE @DHSHIP INT,
    DECLARE @PHISHIP_1 MONEY,
    DECLARE @PVCDT INT,
    DECLARE @KC INT,
    DECLARE @PHISHIP_2 MONEY,
    DECLARE @GBDT INT,
    DECLARE @GIADT MONEY,
    DECLARE @SL INT,
    DECLARE @DTID VARCHAR(5),
    DECLARE @CHXUAT VARCHAR(5),
    DECLARE @CHBAN VARCHAR(5)

	SELECT @ORDERID = MADH, @DTID = MADT, @SL = SLmua, @CHXUAT = MaCHXuat, 
	FROM inserted

    SELECT @DHSHIP = KCSHIP, @CHBAN = MACHBAN
    FROM DONHANG 
    WHERE MADH = @ORDERID

    SELECT @PHISHIP_1 = PHISHIP
    FROM CUAHANG
    WHERE MACH = @CHBAN

    SET @PVCDH = @DHSHIP * @DHSHIP

    SELECT @KC = KHOANGCACH,
    FROM KHOANGCACH
    WHERE MACH1 = @CHBAN
    AND MACH2 = @CHXUAT

    SELECT @PHISHIP_2 = PHISHIP
    FROM CUAHANG
    WHERE MACH = @CHXUAT

    SET @PVCDT = @KC * @PHISHIP_2

    SELECT @GIADT = GIABAN
    FROM DIENTHOAI
    WHERE MADT = @DTID
    AND MACHLTRU = @CHXUAT

    SET @GBDT = @GIADT * @SL

    BEGIN 
        UPDATE DONHANG 
        SET TRIGIADH = (@PVCDT * @GBDT) + @PVCDH 
        WHERE MADH = @ORDERID
    END
END;

